export type Sex = "M" | "F" | "-";

export type EncounterType = "AMBULATORY" | "INPATIENT" | "TRAUMA" | "MASCAL" | "SURGERY";

export type EncounterStatus = "arrived" | "triaged" | "in_treatment" | "discharged";

export type Disposition = "Pending" | "Admit" | "Discharge" | "Transfer" | null;

export type Vitals = {
  hr?: number;
  bpSystolic?: number;
  bpDiastolic?: number;
  rr?: number;
  spo2?: number;
  etcO2?: number;
  temperature?: number;
  painScore?: number;
  recordedAt: string;
};

export type Patient = {
  id: string;
  idNumber: string;
  firstName: string;
  lastName: string;
  age: number;
  sex: Sex;
  allergies?: string[];
  conditions?: string[];
  medications?: string[];
  bloodType?: string;
};

export type Encounter = {
  id: string;
  patientId: string;
  encounterType: EncounterType;
  status: EncounterStatus;
  /** When the encounter entered its current status (ISO string). Used for state-duration analytics. */
  statusEnteredAt?: string;
  location: string;
  presentingProblem: string;
  news2: number;
  arrivalTime: string;
  careTeam: string[]; // Array of user IDs who are following this encounter
  disposition: Disposition;
  vitals: Vitals[];
};

export const seededPatients: Patient[] = [
  {
    id: "p1",
    idNumber: "000000101",
    firstName: "John",
    lastName: "Doe",
    age: 42,
    sex: "M",
    allergies: ["Penicillin"],
    conditions: ["Hypertension"],
    medications: ["Lisinopril"],
    bloodType: "O+",
  },
  {
    id: "p2",
    idNumber: "000000102",
    firstName: "Maria",
    lastName: "Lopez",
    age: 67,
    sex: "F",
    allergies: [],
    conditions: ["COPD", "Diabetes"],
    medications: ["Metformin", "Albuterol"],
    bloodType: "A+",
  },
  {
    id: "p3",
    idNumber: "000000103",
    firstName: "Aarav",
    lastName: "Sharma",
    age: 29,
    sex: "M",
    allergies: ["Latex"],
    conditions: [],
    medications: [],
    bloodType: "B+",
  },
  {
    id: "p4",
    idNumber: "000000104",
    firstName: "Fatima",
    lastName: "Khan",
    age: 51,
    sex: "F",
    allergies: ["Aspirin"],
    conditions: ["Asthma"],
    medications: ["Inhaler"],
    bloodType: "AB+",
  },
  {
    id: "p5",
    idNumber: "000000105",
    firstName: "James",
    lastName: "Peterson",
    age: 74,
    sex: "M",
    allergies: ["Penicillin", "Sulfa"],
    conditions: ["Hypertension", "Diabetes", "Heart Disease"],
    medications: ["Metformin", "Lisinopril", "Aspirin"],
    bloodType: "O-",
  },
  {
    id: "p6",
    idNumber: "000000106",
    firstName: "Sophie",
    lastName: "Williams",
    age: 33,
    sex: "F",
    allergies: [],
    conditions: [],
    medications: [],
    bloodType: "A+",
  },
  {
    id: "p7",
    idNumber: "000000107",
    firstName: "Daniel",
    lastName: "Kim",
    age: 58,
    sex: "M",
    allergies: ["Iodine"],
    conditions: ["Hypertension"],
    medications: ["Amlodipine"],
    bloodType: "B+",
  },
  {
    id: "p8",
    idNumber: "000000108",
    firstName: "Isabella",
    lastName: "Garcia",
    age: 22,
    sex: "F",
    allergies: [],
    conditions: [],
    medications: [],
    bloodType: "O+",
  },
  {
    id: "p9",
    idNumber: "000000109",
    firstName: "Michael",
    lastName: "Brown",
    age: 63,
    sex: "M",
    allergies: ["Penicillin"],
    conditions: ["Diabetes", "Kidney Disease"],
    medications: ["Metformin", "Insulin"],
    bloodType: "A-",
  },
  {
    id: "p10",
    idNumber: "000000110",
    firstName: "Liam",
    lastName: "O'Connor",
    age: 46,
    sex: "M",
    allergies: [],
    conditions: ["Hypertension"],
    medications: ["Lisinopril"],
    bloodType: "O+",
  },
  {
    id: "p11",
    idNumber: "000000111",
    firstName: "Ananya",
    lastName: "Rao",
    age: 37,
    sex: "F",
    allergies: ["Shellfish"],
    conditions: [],
    medications: [],
    bloodType: "B+",
  },
  {
    id: "p12",
    idNumber: "000000112",
    firstName: "Robert",
    lastName: "Johnson",
    age: 81,
    sex: "M",
    allergies: ["Penicillin"],
    conditions: ["Dementia", "Hypertension", "Heart Disease"],
    medications: ["Donepezil", "Lisinopril", "Aspirin"],
    bloodType: "O+",
  },
  {
    id: "p13",
    idNumber: "000000113",
    firstName: "Emily",
    lastName: "Clark",
    age: 19,
    sex: "F",
    allergies: [],
    conditions: [],
    medications: [],
    bloodType: "A+",
  },
  {
    id: "p14",
    idNumber: "000000114",
    firstName: "Carlos",
    lastName: "Martinez",
    age: 55,
    sex: "M",
    allergies: ["Latex"],
    conditions: ["Diabetes"],
    medications: ["Metformin"],
    bloodType: "AB+",
  },
  {
    id: "p15",
    idNumber: "000000115",
    firstName: "Mei",
    lastName: "Chen",
    age: 48,
    sex: "F",
    allergies: [],
    conditions: ["Hypertension"],
    medications: ["Amlodipine"],
    bloodType: "B+",
  },
];

export const seededEncounters: Encounter[] = [
  {
    id: "e1",
    patientId: "p1",
    encounterType: "AMBULATORY",
    status: "triaged",
    location: "Triage",
    presentingProblem: "Chest pain",
    news2: 2,
    arrivalTime: new Date(Date.now() - 12 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e2",
    patientId: "p2",
    encounterType: "INPATIENT",
    status: "in_treatment",
    location: "ED Zone A",
    presentingProblem: "Shortness of breath",
    news2: 5,
    arrivalTime: new Date(Date.now() - 45 * 60000).toISOString(),
    careTeam: ["user1"],
    disposition: null,
    vitals: [],
  },
  {
    id: "e3",
    patientId: "p4",
    encounterType: "SURGERY",
    status: "triaged",
    location: "Medical Ward",
    presentingProblem: "Appendicitis",
    news2: 1,
    arrivalTime: new Date(Date.now() - 70 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e4",
    patientId: "p7",
    encounterType: "TRAUMA",
    status: "in_treatment",
    location: "Trauma Bay",
    presentingProblem: "Motor vehicle accident",
    news2: 6,
    arrivalTime: new Date(Date.now() - 8 * 60000).toISOString(),
    careTeam: ["user1"],
    disposition: null,
    vitals: [],
  },
  {
    id: "e5",
    patientId: "p12",
    encounterType: "INPATIENT",
    status: "triaged",
    location: "Waiting Room",
    presentingProblem: "Fever and confusion",
    news2: 4,
    arrivalTime: new Date(Date.now() - 30 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e6",
    patientId: "p13",
    encounterType: "AMBULATORY",
    status: "arrived",
    location: "Waiting Room",
    presentingProblem: "Ankle sprain",
    news2: 0,
    arrivalTime: new Date(Date.now() - 5 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e7",
    patientId: "p3",
    encounterType: "AMBULATORY",
    status: "triaged",
    location: "Clinic",
    presentingProblem: "Rash and itching",
    news2: 1,
    arrivalTime: new Date(Date.now() - 25 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e8",
    patientId: "p5",
    encounterType: "INPATIENT",
    status: "in_treatment",
    location: "ED Zone B",
    presentingProblem: "Hypertensive crisis",
    news2: 7,
    arrivalTime: new Date(Date.now() - 20 * 60000).toISOString(),
    careTeam: ["user1"],
    disposition: null,
    vitals: [],
  },
  {
    id: "e9",
    patientId: "p6",
    encounterType: "AMBULATORY",
    status: "triaged",
    location: "Triage",
    presentingProblem: "Headache",
    news2: 0,
    arrivalTime: new Date(Date.now() - 18 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e10",
    patientId: "p8",
    encounterType: "AMBULATORY",
    status: "arrived",
    location: "Waiting Room",
    presentingProblem: "Abdominal pain",
    news2: 2,
    arrivalTime: new Date(Date.now() - 10 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e11",
    patientId: "p9",
    encounterType: "INPATIENT",
    status: "triaged",
    location: "ICU",
    presentingProblem: "Diabetic emergency",
    news2: 5,
    arrivalTime: new Date(Date.now() - 35 * 60000).toISOString(),
    careTeam: ["user1"],
    disposition: null,
    vitals: [],
  },
  {
    id: "e12",
    patientId: "p10",
    encounterType: "TRAUMA",
    status: "in_treatment",
    location: "Trauma Bay",
    presentingProblem: "Fall from height",
    news2: 4,
    arrivalTime: new Date(Date.now() - 15 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e13",
    patientId: "p11",
    encounterType: "AMBULATORY",
    status: "triaged",
    location: "Clinic",
    presentingProblem: "Allergic reaction",
    news2: 3,
    arrivalTime: new Date(Date.now() - 22 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e14",
    patientId: "p14",
    encounterType: "INPATIENT",
    status: "triaged",
    location: "Radiology",
    presentingProblem: "Uncontrolled diabetes",
    news2: 3,
    arrivalTime: new Date(Date.now() - 28 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
  {
    id: "e15",
    patientId: "p15",
    encounterType: "AMBULATORY",
    status: "triaged",
    location: "Triage",
    presentingProblem: "Dizziness and nausea",
    news2: 2,
    arrivalTime: new Date(Date.now() - 16 * 60000).toISOString(),
    careTeam: [],
    disposition: null,
    vitals: [],
  },
];

